const data = {
    products: [
        {
            _id: '1',
            name: 'Nike Slim Shirt',
            category: 'Shirts',
            image: '/images/p1.jpg',
            price: 120,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'High quality Nike product',
        },
        {
            _id: '2',
            name: 'Adidas Fit Shirt',
            category: 'Shirts',
            image: '/images/p2.jpg',
            price: 100,
            brand: 'Adidas',
            rating: 4.0,
            numReviews: 10,
            description: 'High quality Adidas product',
        },
        {
            _id: '3',
            name: 'Lacoste Free Shirt',
            category: 'Shirts',
            image: '/images/p3.jpg',
            price: 220,
            brand: 'Lacoste',
            rating: 4.8,
            numReviews: 17,
            description: 'High quality Lacoste product',
        },
        {
            _id: '4',
            name: 'Nike Slim Pants',
            category: 'Pants',
            image: '/images/p4.jpg',
            price: 78,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 14,
            description: 'High quality Nike product',
        },
        {
            _id: '5',
            name: 'Puma Slim Pants',
            category: 'Pants',
            image: '/images/p5.jpg',
            price: 65,
            brand: 'Puma',
            rating: 4.5,
            numReviews: 10,
            description: 'High quality Puma product',
        },
        {
            _id: '6',
            name: 'Elegant Senior Pants',
            category: 'Pants',
            image: '/images/p6.jpg',
            price: 139,
            brand: 'Elegant Tailoring',
            rating: 4.5,
            numReviews: 15,
            description: 'High quality Elegant Tailoring product',
        }
    ]
}

export default data;